= ghrpkg
:toc: left
:sectnums:

ghrpkgはGitHubReleaseでインストールするコマンドのバージョン管理をするためのコマンドです。

WIP

== モチベーション

`apt` なり `yum` なりのOSに付属のパッケージ管理システムがあると、インストールす
るコマンドのバージョン管理ができて便利です。

しかしながら、GitHubReleaseだけに公開されている便利なコマンドなどのバージョン管
理は各人に委ねられている状態だと思います。

たとえば以下。

[source,bash]
----
cd /tmp
wget https://github.com/itchyny/mmv/releases/download/v0.1.2/mmv_v0.1.2_linux_amd64.tar.gz
tar xzf mmv_v0.1.2_linux_amd64.tar.gz
mkdir -p ~/bin
install -m 0755 ./mmv ~/bin/
----

このように手動インストールしたコマンド類をアップグレードしたい場合、
上記と同じような手順で再度インストールし直す必要があります。

この問題を解決することが、このコマンドのモチベーションです。

== 使い方

最初に `init` サブコマンドで設定ファイルを作成します。

その後 `install` サブコマンドでGitHubのリリースURLを渡すと、生成された設定ファイ
ルに記載のパスにインストールされます。初期設定では `~/ghrpkg/bin` にシンボリック
リンクが作成されます。
それらの設定ファイルの実体は `~/ghrpkg/pkg/<owner>/<repo>` に保存されます。

コマンドとしては以下の実行をします。

[source,bash]
----
ghrpkg init
ghrpkg install https://github.com/itchyny/mmv/releases/download/v0.1.2/mmv_v0.1.2_linux_amd64.tar.gz
----

インストールされたコマンドとパッケージの情報は `~/ghrpkg/pkg/<owner>/<repo>` に
保存されます。バージョンアップの際はこのパッケージディレクトリ配下のJSONを元に実
行されます。

最新版にアップグレードする際は以下のコマンドを実行します。

[source,bash]
----
ghrpkg upgrade itchyny/mmv
----

これは `ghrpkg upgrade <owner>/<repo>` というルールに従っています。
バージョンを指定したい場合は以下のコマンドを実行します。

[source,bash]
----
ghrpkg upgrade itchyny/mmv v0.1.2
----

インストールしたコマンドをすべてアップグレードしたい場合は、以下のコマンドを実行
します。

[source,bash]
----
ghrpkg upgrade --all
----

インストール可能なバージョンを確認したい場合は、以下のコマンドを実行します。

[source,bash]
----
ghrpkg show itchyny/mmv
----

インストール済みのパッケージ一覧の確認は以下のコマンドを実行します。

[source,bash]
----
ghrpkg list
----

アップグレード可能なパッケージ一覧の確認は以下のコマンドを実行します。

[source,bash]
----
ghrpkg list --upgradable
----

インストールしたパッケージをアンインストールする場合は、以下のコマンドを実行しま
す。

[source,bash]
----
ghrpkg remove itchyny/mmv
----

削除の確認をしたい場合は、 `--dry` をつけます。

[source,bash]
----
ghrpkg remove --dry itchyny/mmv
----

== インストール

WIPなので提供してません。

== LICENSE

MIT
