---
name: test

"on":
  push:
    branches:
      - master
    paths:
      - 'go.mod'
      - 'go.sum'
      - '**.go'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - 'go.mod'
      - 'go.sum'
      - '**.go'
      - '.github/workflows/test.yml'

env:
  go-version: '1.19'

jobs:
  test:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - os: windows
            runs-on: windows-latest
            opts: -cover -tags windows
          - os: linux
            runs-on: ubuntu-latest
            opts: -cover
          - os: darwin
            runs-on: macOS-latest
            opts: -cover
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ env.go-version }}
      - run: go build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: amd64
      - run: go vet .
      - run: go test ${{ matrix.opts }} ./...
